#!/usr/bin/env python3
from __future__ import annotations
import argparse, json, time
from pathlib import Path
STAGE_ID='OBSERVABILITY_TRACE_SPAN_LEDGER_STAGE3_TRACKER_CAUSAL_TIMELINE_BINDING'
def utc_now(): return time.strftime('%Y%m%dT%H%M%SZ', time.gmtime())
def load(p): return json.loads(Path(p).read_text(encoding='utf-8'))
def main(argv=None):
    ap=argparse.ArgumentParser(); ap.add_argument('--root', required=True); ap.add_argument('--write-report', action='store_true')
    args=ap.parse_args(argv); root=Path(args.root).resolve(); issues=[]; checks=[]
    req=[
        'runtime/traces/observability/TRACE_SPAN_LEDGER_INDEX_LATEST.json',
        'runtime/traces/observability/CAUSAL_STAGE_GRAPH_LATEST.json',
        'runtime/traces/observability/TRACE_SPAN_LEDGER_LATEST.jsonl',
        'runtime/state/operator_surface/OPERATOR_CAUSAL_TIMELINE_LATEST.json',
        'runtime/state/operator_surface/OPERATOR_CAUSAL_TIMELINE_PREVIEW_LATEST.md',
        'OPEN_OPERATOR_VISUAL_TRACKER.html'
    ]
    for rel in req:
        ok=(root/rel).is_file() and (root/rel).stat().st_size>0
        checks.append({'path':rel,'exists_nonempty':ok})
        if not ok: issues.append({'missing_or_empty':rel})
    if not issues:
        index=load(root/req[0]); graph=load(root/req[1]); model=load(root/req[3]); html=(root/req[5]).read_text(encoding='utf-8')
        if index.get('record_count') != graph.get('summary',{}).get('record_count'):
            issues.append({'record_count_mismatch':{'index':index.get('record_count'),'graph':graph.get('summary',{}).get('record_count')}})
        if model.get('summary',{}).get('record_count') != index.get('record_count'):
            issues.append({'model_index_count_mismatch':{'model':model.get('summary',{}).get('record_count'),'index':index.get('record_count')}})
        if not model.get('timeline'):
            issues.append({'timeline_absent':True})
        if not any(r.get('source_artifact') for r in model.get('timeline',[])):
            issues.append({'source_artifact_binding_absent':True})
        for section in ['hero_status_cards','causal_summary_cards','causal_timeline','evidence_strip','next_action_card']:
            if f'data-section="{section}"' not in html:
                issues.append({'html_missing_section':section})
        for phrase in ['Cause → evidence → next action','Generated by <code>build_operator_tracker_causal_timeline_v1.py</code>']:
            if phrase not in html:
                issues.append({'html_missing_phrase':phrase})
    report={'artifact_type':'OBSERVABILITY_TRACE_SPAN_LEDGER_STAGE3_TRACKER_BINDING_VALIDATION.v1','stage_id':STAGE_ID,'created_utc':utc_now(),'verdict':'PASS' if not issues else 'FAIL','checks':checks,'issues':issues}
    if args.write_report:
        out=root/'runtime/traces/observability/TRACE_SPAN_LEDGER_STAGE3_TRACKER_BINDING_VALIDATION_LATEST.json'
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(json.dumps(report, indent=2, sort_keys=True)+'\n', encoding='utf-8')
    print(json.dumps(report, indent=2, sort_keys=True))
    return 0 if not issues else 2
if __name__=='__main__': raise SystemExit(main())
